---
title: "Oncomouse Course Site"
url: "https://oncomouse.github.io"
baseurl: "/courses"
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Readme.md
  - _scripts/

theme: jekyll-theme-minimal