---
title: "Deanna Stover Course Site"
url: "https://deanna-stover.github.io"
baseurl: "/courses"
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Readme.md
  - _scripts/

theme: jekyll-theme-minimal
